SAM-196 Create config distribution, GHA Workflow to automate it
kbase/sample_service_validator_config pull request #46
Opened 2022-03-15 00:20 UTC by eapearson

## Purpose

This set of changes has two major thrusts.

First, it adds support for placing the generated spec files into a distribution folder.

Secondly, it adds GitHub Action Workflow support to automate the creation of spec distributions.

## Spec Distributions

A spec distribution is simply a copy of the source or generated spec files which are currently utilized by the Sample Service and Sample Uploader.

A new make task copies these files into the `dist` folder. The `dist` folder is excluded from git commits.

## GHA Workflow

Two GHA Workflows support the automated generation of specs, packaging into the dist, and publication of special dist branches.

### `build-push.yml`

The primary workflow `build-push.yml` is responsible for:

- validating source specs
  
- generating specs
  
- placing into dist directory
  
- creating a special dist branch
  
- tagging the release dist branch with the version upon release
  

The dist branch is simply a branch created with a name as described below, and containing the contents of the dist directory. This creates a very small branch which an be readily fetched by code which requires it.

This workflow is triggered by pull request activity, merges to main, and releases.

All dist branches are prefixed with `dist-`

For a pull request trigger, the branch is named `dist-pull_request-#` where `#` is the pull request number.

For a merge to master, the branch is named `dist-master`.

For a release, the branch is named `dist-release` which is also tagged with the tag `dist-release-v#.#.#`, where `v#.#.#` is the tag and should have the form of a semantic version prefixed with the letter "v".

### `delete-closed-pr-dist-branch.yml`

A small workflow takes care of removing a the dist branch associated with a pull request when that pull request is merged.

The end result, after some usage, is that there are permanent, evergreen distribution branches `dist-master` and `dist-release`, and a growing set of version tags `dist-release-v#.#.#`.

## Miscellaneous Changes

- add `RELEASE_NOTES.md`
  
- consolidate markdown docs into `docs` directory
  
- add new docs to cover this functionality
  
- remove unused travis config
  
- fix missing pandas in requirements.txt
  
- update copyright date

2022-03-15 22:24 UTC, eapearson commented
@dauglyon there are a couple of ways to get a branch or tag from GitHub w/o downloading the entire repo and history.

You can clone with --depth 1. This will just download the branch w/o history. It is small (about 20K compressed). This does include the .git directory.

You can also download an archive like
curl -L --output dist-release.zip https://github.com/eapearson/sample_service_validator_config/archive/refs/tags/dist-release-v1.0.1.zip (or .tar.gz).
A pro is that .git directory does not need to be removed or omitted when copied, the con is that you need to unpack it. Otherwise It is about the same size as a depth 1 clone, a bit smaller since it doesn't have the .git.

The advantage of this approach is that one does not need to release or pre-release. E.g. a PR can be evaluated directly instead of merging and creating a pre-release, or main can be used e.g. in CI between releases.

2022-03-16 17:09 UTC, scanon reviewed
Nothing major

2022-03-16 17:28 UTC, eapearson commented on LICENSE.md
> +Copyright (c) 2020-2022 The KBase Project and its Contributors
Didn't we discuss this a few weeks ago? At that time I looked into best practices, and the advice was that the copyright should cover a date range which matches when the material is published.

2022-03-16 17:29 UTC, eapearson commented on requirements.txt
> +pandas==1.3.5
Yes. The build fails if it is not installed.
https://github.com/kbase/sample_service_validator_config/blob/faa058202f41cb7eb5e43303d6dd5e7e92231d32/scripts/create_tsv.py#L3

2022-03-16 17:32 UTC, scanon commented on LICENSE.md
> +Copyright (c) 2020-2022 The KBase Project and its Contributors
I don't think this is true.  Just leave it as is.  We haven't been doing this on any other repos.

2022-03-16 17:32 UTC, scanon commented on requirements.txt
> +pandas==1.3.5
Okay.  I didn't see it in the changes.

2022-03-16 17:34 UTC, scanon requested changes

2022-03-16 17:43 UTC, eapearson commented on LICENSE.md
> +Copyright (c) 2020-2022 The KBase Project and its Contributors
E.g. at google they provide this format, but do say that updating the copyright when a work is modified is optional:

https://opensource.google/documentation/reference/copyright

Or twitter bootstrap:

Copyright (c) 2011-2022 Twitter, Inc.
Copyright (c) 2011-2022 The Bootstrap Authors

IBM

The MIT License (MIT)

Copyright (c) 2019-2020 IBM

Some from Apple's swift repo - they don't appear to be very consistent:

# Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
// Copyright (c) 2020 Apple Inc. and the Swift project authors
Copyright (c) 1815, Napoleon Bonaparte. All rights reserved.

2022-03-16 18:41 UTC, eapearson commented on .github/workflows/build-dist.yml
> +        uses: s0/git-publish-subdir-action@develop
I'm quite sure this is how I originally described and had prototyped this ;)

I think by "standard" you mean, directly supported by GitHub. (Using tagged branches (with the branches sometimes deleted) to store build assets is not as uncommon as you might think - e.g. commonly used for js libraries.) GitHub releases store the attached assets outside of git, one benefit of which is not to clutter git with things like large binaries, and also so that downloads don't go through git.

In any case, no big deal, this can easily be switched to store the build assets in a release.

What will be lost is the ability to access build assets without a release, i.e. a PR or even a feature branch (although that trigger was not included here intentionally.)

2022-03-17 00:22 UTC, eapearson commented on .github/workflows/build-dist.yml
> +        uses: s0/git-publish-subdir-action@develop
The change is in place to upload the generated assets to a release.
I can't be actually verified here, of course, because it needs to be merged before it will work. But you can check out my fork where I've been exercising it.
I've also exercised it with the beginnings of the change to support it in the sample service, by fetching the distribution zip file, and expanding it. Also tested fetching it 200 times back to back to determine if it would be affected by rate limits without authentication using the public url.  At that scale, at least, rate limitation was not triggered.

2022-03-21 23:47 UTC, scanon approved these changes
LGTM.  We may tweak some of the artifacts and which branches, but we can do that in a subsequent PR.

2022-03-21 23:47 UTC, merged